= Introduction

Welcome to the Axon Manual!

Axon provides the Axon Framework and the Axon Server to help build applications centered on three core concepts - CQRS (Command Query Responsibility Segregation) / Event Sourcing and DDD (Domain Driven Design).

While many types of applications can be built using Axon, it has proven to be very popular for microservices architectures.
Axon provides an innovative and powerful way of sensibily evolving to event-driven microservices within a microservices architecture.

Please visit https://axoniq.io/[the AxonIQ website] to learn more about AxonIQ and the Axon community.
There, you will find information about Axon training, support options, upcoming and past events.

== How to use this guide

The Reference Guide is split into 4 sections

|===
| Section Name | Purpose

| xref:./getting-started/quick-start.adoc[Quick Start]
| Details the Quick Start toolkit that Axon provides to easily familiarize with the basic concepts of Axon Framework and Axon Server

| xref:./axon-framework/introduction.adoc[Axon Framework]
| Details the building of Axon Framework based applications.

| xref:./axon-server/introduction.adoc[Axon Server]
| Details the Installation/Setup and Maintenance of Axon Server (SE/EE).

| link:release-notes/rn-extensions[Axon Framework Extensions]
| Details the extensions that Axon Framework provides to integrate with existing enterprise infrastructure(s).
|===

== License(s)

The Axon platform consists of Axon Framework and Axon Server.
It is provided by AxonIQ B.V.
under the licenses described below.

* Axon Framework, as well as the Axon documentation and sample programs, are open source and provided under the http://www.apache.org/licenses/LICENSE-2.0[Apache License v2.0].
* For Axon Server, licensing depends on the version.
 ** The standard version, called "Axon Server", is open source and free to download and use.
It is provided under an AxonIQ-specific open source license.
While this license allows you to run the software freely in any environment, it is less permissive than the Apache License.
For instance, it doesn't allow you as a licensee to create a derivative work.
 ** The commercial version, called "Axon Server Enterprise", as well as the various "Packs", are closed source and provided under a commercial license agreement.

If you have any questions about licensing, or want to obtain a license to our commercial software, please contact us via https://axoniq.io[axoniq.io] or link:mailto:sales@axoniq.io[sales@axoniq.io].
