= Access Control and the CLI

When access control has been enabled, you may initially find yourself without a user account for the UI.
xref:../administration/admin-configuration/cluster-template.adoc[Cluster templates] can be used to combine the initial configuration of your replication groups, registrations of client application, and a core set of user accounts, but you can also use the CLI to do this.
For this you still need an admin-level token, which for Axon Server SE xref:./access-control-se.adoc[can be configured in the properties].
For Axon Server EE such a token is by default xref:./access-control-ee.adoc[generated by Axon Server itself], and stored in a file named "[.code]``./security/.token``".
This default location is known by the CLI, so if you run in in the working directory of Axon Server, it will check for that file and automatically use the token.
If you have overridden the location or provided your own file with a token, for example to ensure that all nodes use the same token, then you must use the "``-t`` _<token>_" option to provide it to the CLI.
