= Events

The second type of "Messages" that an Axon application is associated with are _*Event Messages (or simply Events).*_ This section of the reference guide intends to cover in detail the capabilities that the Axon Framework provides to help facilitate Event Message Development.

A summary of the various sub-sections is given below.

|===
| Sub-Section | Purpose

| xref:./event-dispatchers.adoc[Event Dispatchers] / xref:event-handlers.adoc[Event Handlers]
| Functional development for Event Messages using the Axon Framework

| xref:./event-processors/README.adoc[Event Processors] / xref:event-bus-and-event-store.adoc[Event Bus & Event Store]
| Non-Functional development for Event Messages using the Axon Framework

| xref:./event-versioning.adoc[Event Versioning]
| Details on Event versioning capabilities provided by the Axon Framework
|===

This guide is complemented by a video tutorial which gives a practical demonstration of the concepts explained in this section.
The tutorial is available at -> https://www.youtube.com/watch?v=jS1vfc5EohM&feature=youtu.be[Axon Coding Tutorial - Event Messages]
