= Major Releases

This page notes all enhancements and features that we have introduced to our major releases of the Axon AMQP Extension.

== Release 4.6

If you're curious about the dependency upgrades made in this release we refer to https://github.com/AxonFramework/extension-amqp/releases/tag/axon-amqp-4.6.0[this] page.

=== Enhancements

* Change how Sonar is invoked for GHAs https://github.com/AxonFramework/extension-amqp/pull/162[#162]
* Added an AMQP sample to show how to use the extension https://github.com/AxonFramework/extension-amqp/pull/126[#126]
* Splitted builds into pr and not pr, added ghactions to dependabot and other minors https://github.com/AxonFramework/extension-amqp/pull/88[#88]

=== Bug Fixes

* Precision on Date Time Utils https://github.com/AxonFramework/extension-amqp/issues/94[#94]

=== Contributors

We'd like to thank all the contributors who worked on this release!

* https://github.com/smcvb[@smcvb]
* https://github.com/lfgcampos[@lfgcampos]

== Release 4.5

* Issue https://github.com/AxonFramework/extension-amqp/pull/5[#5] introduces dependabot.
This updated a large amount of the versions used by this extension.
* We updated all tests to a more current testing solution.
This means we introduced https://www.testcontainers.org/[Testcontainers] and updated JUnit to version 5.
You can find the made changes in https://github.com/AxonFramework/extension-amqp/pull/44[this] pull request.

You can check https://github.com/AxonFramework/extension-amqp/releases/tag/axon-amqp-4.5[this] page for a complete list of all changes.

== Release 4.4

* Issue https://github.com/AxonFramework/extension-amqp/pull/3[#3] introduces support for Spring Boot Developer Tools.
* We introduce dependabot, which updated the log4j version.

== Release 4.3

We did not introduce any significant changes other than updating the extension to use Axon Framework release 4.3.

== Release 4.2

We did not introduce any significant changes other than updating the extension to use Axon Framework release 4.2.

== Release 4.1

A version predicament caused the extension to load the wrong package for the `ChannelAwareMessageListener`.
We resolved this issue for release 4.1 https://github.com/AxonFramework/extension-amqp/issues/1[here].

Furthermore, we updated the dependency on Axon Framework to 4.1.

== Release 4.0

We split off the AMQP logic from Axon Framework core into a dedicated repository.
Next to that, it complies with Axon Framework's 4.0 release.
